"""add ai fields to lead_scores

Revision ID: 48aa7df73595
Revises: 6d43b7f73f35
Create Date: 2026-01-31 16:56:52.977198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48aa7df73595'
down_revision: Union[str, Sequence[str], None] = '6d43b7f73f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_scores', sa.Column('urgency_score', sa.Integer(), nullable=True))
    op.add_column('lead_scores', sa.Column('sentiment', sa.String(), nullable=True))
    #op.add_column('lead_scores', sa.Column('ai_entities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('lead_scores', sa.Column('ai_recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_scores', 'ai_recommendation')
    #op.drop_column('lead_scores', 'ai_entities')
    op.drop_column('lead_scores', 'sentiment')
    op.drop_column('lead_scores', 'urgency_score')
    # ### end Alembic commands ###
