"""add phone_number to users

Revision ID: 826fcf8f1158
Revises: bf65e6d1bdd4
Create Date: 2026-02-05 17:39:42.167721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826fcf8f1158'
down_revision: Union[str, Sequence[str], None] = 'bf65e6d1bdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokerages', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokerages', 'phone_number')
    # ### end Alembic commands ###
