"""fix lead_scores schema

Revision ID: ae75810264ef
Revises: e6ac856b026a
Create Date: 2026-01-13 16:12:01.469199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae75810264ef'
down_revision: Union[str, Sequence[str], None] = 'e6ac856b026a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brokerage_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('input_payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_scores')
    # ### end Alembic commands ###
