"""add stripe billing fields

Revision ID: fa393fcca428
Revises: 954342e3eb72
Create Date: 2026-01-18 12:56:51.946287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa393fcca428'
down_revision: Union[str, Sequence[str], None] = '954342e3eb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column("brokerages", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    op.add_column("brokerages", sa.Column("subscription_status", sa.String(), nullable=True))

    # Set defaults for existing rows
    op.execute("UPDATE brokerages SET subscription_status = 'trial' WHERE subscription_status IS NULL")

    # Now enforce NOT NULL
    op.alter_column("brokerages", "subscription_status", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokerages', 'subscription_status')
    op.drop_column('brokerages', 'stripe_customer_id')
    # ### end Alembic commands ###
