import React from 'react';

export default function TermsOfService() {
  // Your official registration number
  const udyamNumber = "UDYAM-KL-02-0149354"; 

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-black mb-3"><span className="text-blue-600">Lead</span>RankerAI</h1>
          <h2 className="text-2xl font-bold text-slate-800">Terms of Service</h2>
          <p className="text-slate-500 text-sm mt-2">Effective: February 27, 2026 · Governing Law: India (Kerala)</p>
        </div>

        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-8 md:p-12 space-y-8 text-slate-700">

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">1. Acceptance of Terms</h3>
            <p className="text-sm leading-relaxed">
              By accessing or using LeadRankerAI ("the Service", "we", "us"), you agree to these Terms of Service. 
              The Service is operated by **LeadRankerAI**, a proprietary firm registered in Kerala, India 
              (MSME Udyam Reg No: {udyamNumber}). If you are using the Service on behalf of a company, 
              you represent that you have authority to bind that company to these terms.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">2. Description of Service</h3>
            <p className="text-sm leading-relaxed">
              LeadRankerAI provides an AI-powered lead scoring platform for real estate brokerages, logistics firms, 
              insurance agencies, and other industries. The Service analyzes customer messages and assigns urgency 
              scores to help you prioritize your sales pipeline.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">3. Subscription Plans & Billing</h3>
            <div className="text-sm leading-relaxed space-y-2">
              <p><strong>Free Trial:</strong> 50 lead scores per month, no credit card required.</p>
              <p><strong>Starter Plan:</strong> ₹1,599/month or $19/month — 1,000 leads/month.</p>
              <p><strong>Team Plan:</strong> ₹4,099/month or $49/month — 5,000 leads/month.</p>
              <p>Billing is monthly and auto-renewed. You may cancel any time from the Billing page. 
                Cancellation takes effect at the end of the current billing period. <strong>No refunds</strong> are 
                issued for partial months, unused credits, or early cancellation.</p>

            <p>Payments are processed securely by <strong>Razorpay</strong> (India).We do not store card details.</p>
            </div>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">4. Acceptable Use</h3>
            <div className="text-sm leading-relaxed space-y-2">
              <p>You agree NOT to:</p>
              <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
                <li>Reverse engineer, scrape, or resell the AI scoring engine.</li>
                <li>Submit illegal, harmful, or fraudulent data to the platform.</li>
                <li>Use the platform to score leads for illegal services.</li>
                <li>Share your account credentials with unauthorized parties.</li>
                <li>Exceed plan limits through automated or artificial means.</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">5. Data Ownership</h3>
            <p className="text-sm leading-relaxed">
              You retain full ownership of all lead data you submit. LeadRankerAI does not sell, share, or 
              use your lead data for any purpose other than providing the scoring service to your account. 
              You grant us a limited, non-exclusive license to process your data solely to provide the Service.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">6. AI Accuracy Disclaimer</h3>
            <p className="text-sm leading-relaxed">
              Lead scores are generated by AI and are <strong>advisory in nature only</strong>. They do not 
              constitute financial, legal, or business advice. LeadRankerAI makes no warranty that scores are 
              accurate, complete, or suitable for any specific business purpose. You are solely responsible 
              for decisions made based on scores.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">7. Limitation of Liability</h3>
            <p className="text-sm leading-relaxed">
              To the maximum extent permitted by applicable Indian law, LeadRankerAI's total liability for 
              any claim shall not exceed the amount you paid in the 3 months prior to the claim. We are not 
              liable for indirect, incidental, consequential, or punitive damages including lost profits, 
              data loss, or business interruption.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">8. Termination</h3>
            <p className="text-sm leading-relaxed">
              We may suspend or terminate your account for material breach of these terms, non-payment, or 
              illegal activity. You may delete your account at any time from Settings. Upon deletion, all 
              your data is permanently removed within 30 days as per our privacy policy.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">9. Governing Law & Jurisdiction</h3>
            <p className="text-sm leading-relaxed">
              These Terms are governed by the laws of India. Any dispute shall first be attempted through 
              mutual resolution. If unresolved, disputes will be subject to the exclusive jurisdiction of courts in 
              <strong> Ernakulam, Kerala, India</strong>. For international clients, arbitration under the Indian 
              Arbitration and Conciliation Act, 1996 shall apply.
            </p>
          </section>

          <section>
            <h3 className="font-black text-slate-900 text-lg mb-3">10. Contact</h3>
            <p className="text-sm leading-relaxed">
              Questions about these Terms: <a href="mailto:legal@leadrankerai.com" 
                className="text-blue-600 hover:underline">legal@leadrankerai.com</a><br/>
              <strong>LeadRankerAI</strong><br/>
              Registered MSME: {udyamNumber}<br/>
              Ernakulam, Kerala, India
            </p>
          </section>
        </div>

        <p className="text-center text-xs text-slate-400 mt-8">
          Last updated February 27, 2026 · <a href="/privacy" className="hover:underline text-blue-500">Privacy Policy</a>
        </p>
      </div>
    </div>
  );
}